language: python
python:
- 3.8
services:
- postgresql
install:
- psql -c 'create database django_db owner postgres;' -U postgres
- pip install -r requirements.txt
script:
- python manage.py migrate
- python manage.py test shop/tests/
deploy:
  provider: heroku
  api_key:
    secure: FmdfR4SgbLSTY3emFc4DDiFF11x/NoVL5/oqnG2tGKfWaoQS6Kegz1yLWDMNSuiOk3Yn9ycS4GTI6FR14X4PXaKdadEbkJwKMPLSW1O9BAxHEhjuQnn5l54Z+VHcxryDOmHLGGvs9aKvZwYtEw5V8x3xPD8I87o9Z2pmuVrRCnFQ1bh27gkw7aXldP4jOGwTeJLpfgGu/T5Et/uCjkvIJtgHn0y9yLsJbqbY7hKmA0m02mM3ZJ1UKjdMrz7toYZc1OBh684me5N36qL4VIdb9mUeO2I56x28xUdO27koA9DWCFCxTBgl2F2lSWDBP/wo3+VoQM0GZxrMElRwG+JFfz69r5G88RXb9D8zhn22xyLPbD9sBKxzQgfYftbMCJGULO4OZ1xiSkh+17KH8WQT/hk7wswNCcVFxohWzaAnbrQW/l/YBXVmBghHZvkwBuCjwburIL3MneULSfOXgBxiTzjfoxVfCX36iqnbCV5AdHNOXGXbDTNn1EFgDGjERulWcxxBnMoyx76F5fLLy2wrxBEONxkiwOYFn7yWWR7YhmeSI4iB55Zs9XnArPruJmFx7gMjm2UAcUqz7FJ9aTYNYFQOjC3pVaeQcol907hIQ8bZTRovHPkKsKr1KIZeojES0PgYTUomz5klnl6t6SPG2LB+yynh10JDQN7D5XCfQZI=
  app: webapp-sokolova-v-shop
  run: python manage.py loaddata products.yaml && python manage.py migrate
  on: master
